/*
	CONSULTA QUE RETORNA A QUANTIDADE DE
	TAREFAS POR CADA PRIORIDADE
*/
SELECT
	PRIORIDADE,
	COUNT(ID) AS QTDTAREFAS
FROM TAREFA
WHERE
	DATA_HORA >= '2025-08-01' AND
	DATA_HORA <= '2025-08-31'
GROUP BY
	PRIORIDADE
ORDER BY
	QTDTAREFAS DESC;

/*
	CONSULTA QUE RETORNA A QUANTIDADE DE
	TAREFAS POR CADA CATEGORIA
*/
SELECT
	C.NOME AS CATEGORIA,
	COUNT(T.ID) AS QTDTAREFAS
FROM TAREFA T
INNER JOIN CATEGORIA C
ON C.ID = T.CATEGORIA_ID
WHERE
	T.DATA_HORA >= '2025-08-01' AND
	T.DATA_HORA <= '2025-08-31'
GROUP BY
	C.NOME
ORDER BY
	QTDTAREFAS DESC;
