INSERT INTO CATEGORIA(ID, NOME)
	VALUES
		(NEWID(), 'TRABALHO'),
		(NEWID(), 'ESTUDO'),
		(NEWID(), 'FAMÍLIA'),
		(NEWID(), 'LAZER'),
		(NEWID(), 'OUTROS');
GO

SELECT * FROM CATEGORIA
ORDER BY NOME ASC;
GO